services:
  # 1. BACKEND
  backend:
    build: ./backend
    container_name: foodmap_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  # 2. FRONTEND
  frontend:
    build: ./frontend
    container_name: foodmap_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend